name: Master Flow

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

  lint:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run ktlint
        run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.43.2/ktlint && chmod a+x ktlint && ./ktlint

  test-app:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt secrets
        run: ./.github/scripts/decrypt_secrets.sh
        env:
          KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
      - name: Run Unit Tests
        run: ./gradlew :app:testDebugUnitTest

  test-ui-repository:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt secrets
        run: ./.github/scripts/decrypt_secrets.sh
        env:
          KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
      - name: Run Unit Tests
        run: ./gradlew :repository:testDebugUnitTest

  test-ui-discover:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt secrets
        run: ./.github/scripts/decrypt_secrets.sh
        env:
          KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
      - name: Run Unit Tests
        run: ./gradlew :ui-discover:testDebugUnitTest

  test-ui-trakt-sync:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt secrets
        run: ./.github/scripts/decrypt_secrets.sh
        env:
          KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
      - name: Run Unit Tests
        run: ./gradlew :ui-trakt-sync:testDebugUnitTest

  test-ui-statistics:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt secrets
        run: ./.github/scripts/decrypt_secrets.sh
        env:
          KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
      - name: Run Unit Tests
        run: ./gradlew :ui-statistics:testDebugUnitTest

  test-ui-statistics-movies:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt secrets
        run: ./.github/scripts/decrypt_secrets.sh
        env:
          KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
      - name: Run Unit Tests
        run: ./gradlew :ui-statistics-movies:testDebugUnitTest

  test-ui-search:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt secrets
        run: ./.github/scripts/decrypt_secrets.sh
        env:
          KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
      - name: Run Unit Tests
        run: ./gradlew :ui-search:testDebugUnitTest

  test-ui-progress-movies:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt secrets
        run: ./.github/scripts/decrypt_secrets.sh
        env:
          KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
      - name: Run Unit Tests
        run: ./gradlew :ui-progress-movies:testDebugUnitTest

  distribute:
    needs: [
        test-app,
        test-ui-repository,
        test-ui-discover,
        test-ui-trakt-sync,
        test-ui-statistics,
        test-ui-statistics-movies,
        test-ui-search,
        test-ui-progress-movies
    ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Decrypt secrets
        run: ./.github/scripts/decrypt_secrets.sh
        env:
          KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}

      - name: Build APK
        run: ./gradlew app:assembleRelease

      - name: Distribute APK
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: owner
          file: app/build/outputs/apk/release/app-release.apk
          releaseNotes: ""

