name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install ktlint
      run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.35.0/ktlint && chmod a+x ktlint
    - name: Run ktlint
      run: ktlint
    - name: Decrypt keystore
      run: ./.github/scripts/decrypt_keystore.sh
      env:
        KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
    - name: Build with Gradle
      run: ./gradlew assembleDebug
