name: Android Checks & Tests

on:
  push:
    branches:
      - master

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Decrypt secrets
      run: ./.github/scripts/decrypt_secrets.sh
      env:
        KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
    - name: Run ktlint
      run: curl -sSLO https://oss.sonatype.org/content/repositories/snapshots/com/pinterest/ktlint/0.42.0-SNAPSHOT/ktlint-0.42.0-20210720.195816-23-all.jar && chmod a+x ktlint-0.42.0-20210720.195816-23-all.jar && java -jar ktlint-0.42.0-20210720.195816-23-all.jar
    - name: Run Unit Tests (app)
      run: ./gradlew :app:testDebugUnitTest
    - name: Run Unit Tests (ui-repository)
      run: ./gradlew :repository:testDebugUnitTest
    - name: Run Unit Tests (ui-discover)
      run: ./gradlew :ui-discover:testDebugUnitTest
